// <auto-generated />
using KMwareWeb01.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KMwareWeb01.Data
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20240201235309_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("KMwareWeb01.DAO.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "k@m.com",
                            Firstname = "K",
                            Lastname = "M",
                            Mobile = "1234567890",
                            NameIdentifier = "KM",
                            Password = "password",
                            Provider = "Cookies",
                            Roles = "Admin",
                            Username = "k@m.com"
                        });
                });

            modelBuilder.Entity("KMwareWeb01.DAO.Models.RunTimes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("V0")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("V7")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("RunTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 2,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 3,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 4,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 5,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 6,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        },
                        new
                        {
                            Id = 7,
                            V0 = 0,
                            V1 = 0,
                            V2 = 0,
                            V3 = 0,
                            V4 = 0,
                            V5 = 0,
                            V6 = 0,
                            V7 = 0
                        });
                });

            modelBuilder.Entity("KMwareWeb01.DAO.Models.Updates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("IsRainDelay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunTimesJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Updates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRainDelay = (byte)0,
                            RunTimesJson = "{\"V0\":0,\"V1\":0,\"V2\":0,\"V3\":0,\"V4\":0,\"V5\":0,\"V6\":0,\"V7\":0}",
                            TimeStamp = "2021-01-01 00:00:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
